kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manageddisk-prem
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
parameters:
  skuname: Premium_LRS
  kind: managed
  cachingMode: None